language: php
dist: trusty

php:
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - hhvm

before_script:
  - composer self-update
  - composer install

script:
  - mkdir -p build/logs
  - phpunit --coverage-clover build/logs/clover.xml tests/

after_script:
  - php vendor/bin/coveralls -v

