language: php
dist: trusty
group: edge

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - nightly

matrix:
  allow_failures:
    - php: nightly

before_script:
  - composer self-update
  - composer install

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml tests/

after_script:
  - php vendor/bin/coveralls -v
